select shipping_type from customers
/*what is total revenue generated by male and female customers*/
select gender, Sum(purchase_amount) as revenue
from customers
group by gender

/*which customer used a discount but spent more than average purchase amount*/
select customer_id , purchase_amount
from customers
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from customers)

/*top 10 products with the highest average review rating*/
select item_purchased,ROUND(avg(review_rating)::numeric,2) 
as "average product rating" 
from customers
group by item_purchased
order by avg(review_rating) desc 
limit 10;

/*compare the average purchase amount between the standard and express shipping*/
select shipping_type,
(avg(purchase_amount),2)
from customers
where shipping_type in ('Standard' , 'Express')
group by shipping_type

/*compare avg spend and total revenue between subscribers and non subscribers*/
select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as average_spend,
round(sum(purchase_amount),2) as total_revenue from customers
group by subscription_status
order by total_revenue, average_spend desc

/*which 5 products have the highest percentage of purchases with discounts applied*/
select item_purchased,
       round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

/*segment customers into new, returning, and loyal.
basead on their total no. of purchases, and show teh count of each segment*/
with customer_type as (
select customer_id , previous_purchases, case when 
previous_purchases = 1 then 'new' 
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from customers)
select customer_segment, count(*) as "number of customers"
from customer_type 
group by customer_segment 

/*top three most purchased products within each category*/
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count (customer_id) desc) as item_rank
from customers
group by category, item_purchased)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

/*are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe*/
select subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases>5
group by subscription_status

/*revenue contribution of each group*/
select age_group,
sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;